/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Praveen
 */
public class AddBooking extends javax.swing.JInternalFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form AddBooking
     */
    String luser;

    public AddBooking(String loginuser) {
        initComponents();
        busSourceCBFillData();
        busDestinationCBFillData();
        this.luser = loginuser;
        

    }

    public void Table1() {
        try {
            String sql = "select booking_id,booking_user,journey_date,bus_no,bus_source,bus_dest,paid,seat,first_name,last_name  From bus_booking where booking_user=? ";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "");
            pst = conn.prepareStatement(sql);
            pst.setString(1, luser);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    public void busSourceCBFillData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();
            String selectQuery = "select distinct(bus_source) as bus_source from bus_details";
            ResultSet rs = stat.executeQuery(selectQuery);
            while (rs.next()) {
                sourceCB.addItem(rs.getString("bus_source"));

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void busDestinationCBFillData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();
            String selectQuery = "select distinct(bus_dest) as bus_dest  from bus_details";
            ResultSet rs = stat.executeQuery(selectQuery);
            while (rs.next()) {
                destinationCB.addItem(rs.getString("bus_dest"));

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dateDP = new org.jdesktop.swingx.JXDatePicker();
        sourceCB = new javax.swing.JComboBox<>();
        destinationCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Source");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Destination");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Search Result.....");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Booking Details......");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Add Booking Info");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dateDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDPActionPerformed(evt);
            }
        });

        sourceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceCBActionPerformed(evt);
            }
        });

        destinationCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationCBActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(371, 371, 371)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(35, 35, 35)
                                                .addComponent(dateDP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)))
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel5)))
                                .addGap(0, 213, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(sourceCB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(destinationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sourceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(destinationCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void infoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }

    private void sourceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceCBActionPerformed

    private void dateDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String source = (String) sourceCB.getSelectedItem();
        String destination = (String) destinationCB.getSelectedItem();
        java.util.Date Date = dateDP.getDate();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String DateFormated = sdf.format(Date);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();
            String selectQuery = "select * from bus_details where bus_source='" + source + "' and bus_dest='" + destination + "' and bus_date = '" + DateFormated + "'";
            ResultSet rs = stat.executeQuery(selectQuery);

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String bus_no = (String) model.getValueAt(index, 1);
        String bus_source = (String) model.getValueAt(index, 2);
        String bus_dest = (String) model.getValueAt(index, 3);
        String bus_date = model.getValueAt(index, 4).toString();
        String bus_time = (String) model.getValueAt(index, 5);
        String price = (String) model.getValueAt(index, 6);
        String avail_seat = (String) model.getValueAt(index, 7);

        BookingFormFrame = new JFrame();
        BookingFormPanel = new JPanel();
        gl = new GridLayout(0, 4);
        l1 = new JLabel("Bus No");
        l11 = new JLabel(bus_no);
        l3 = new JLabel("Bus Source");
        l13 = new JLabel(bus_source);
        l4 = new JLabel("Bus Dest");
        l14 = new JLabel(bus_dest);
        l5 = new JLabel("Depart Date");
        l15 = new JLabel(bus_date);
        l6 = new JLabel("Depart Time");
        l16 = new JLabel(bus_time);
        l7 = new JLabel("Price/seat");
        l17 = new JLabel(price);
        l8 = new JLabel("Available Seat");
        l18 = new JLabel(avail_seat);
        seatnoL = new JLabel("Seat No");
        //idnoL = new JLabel("ID No.");
        fnameL = new JLabel("First Name");
        lnameL = new JLabel("Last Name");
        t1 = new JTextField(20);
        //t2 = new JTextField(20);
        t3 = new JTextField(20);
        t4 = new JTextField(20);

        BookingFormFrame.getContentPane().add(BookingFormPanel);
        BookingFormPanel.setLayout(gl);

        BookingFormPanel.add(l1);
        BookingFormPanel.add(l11);
        //BookingFormPanel.add(l2);
        //BookingFormPanel.add(l12);
        BookingFormPanel.add(l3);
        BookingFormPanel.add(l13);
        BookingFormPanel.add(l4);
        BookingFormPanel.add(l14);
        BookingFormPanel.add(l5);
        BookingFormPanel.add(l15);
        BookingFormPanel.add(l6);
        BookingFormPanel.add(l16);
        BookingFormPanel.add(l7);
        BookingFormPanel.add(l17);
        BookingFormPanel.add(l8);
        BookingFormPanel.add(l18);

        BookingFormPanel.add(seatnoL);
        BookingFormPanel.add(t1);
        //BookingFormPanel.add(idnoL);
       // BookingFormPanel.add(t2);
        BookingFormPanel.add(fnameL);
        BookingFormPanel.add(t3);
        BookingFormPanel.add(lnameL);
        BookingFormPanel.add(t4);

        int result = JOptionPane.showConfirmDialog(BookingFormFrame, BookingFormPanel, "Booking Form", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            String booking_user = luser;
            String seatno = t1.getText();
            //String idno = t2.getText();
            String first_tname = t3.getText();
            String last_name = t4.getText();
            String status="Booked";
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String databaseURL = "jdbc:mysql://localhost:3306/busm";
                Connection con = DriverManager.getConnection(databaseURL, "root", "");
                Statement stat = con.createStatement();
                String selectQuery = "select * from bus_booking where bus_no ='" + bus_no + "' and journey_date='" + bus_date + "' and booking_user='" + booking_user + "' and seat='" + seatno + "' and paid='" + price+ "' and bus_source='" + bus_source+ "' and bus_dest='" + bus_dest + "' ";
                System.out.println(selectQuery);
                ResultSet rs = stat.executeQuery(selectQuery);
                //   System.out.println(rs.next());
                if (rs.next()) {
                    infoMessage("Already Booked", "ALert !!");

                } else {
                    String insertQuery = "insert into bus_booking values(null,'" + booking_user + "','" + bus_date + "','" + bus_no + "','" + bus_source + "','" + bus_dest + "','" + seatno + "','"+ price+ "','"+first_tname + "','" + last_name + "')";

                    int i = stat.executeUpdate(insertQuery);
                    if (i == 1) {

                        int remaining_seat = Integer.parseInt(avail_seat) - 1;//Integer.parseInt(seatno);

                        String updateQuery = "update bus_details set bus_seat='" + remaining_seat + "' where bus_no='" + bus_no + "'  and bus_date='" + bus_date + "'";
                        int j = stat.executeUpdate(updateQuery);
                        if (j == 1) {

                            String source = (String) sourceCB.getSelectedItem();
                            String destination = (String) destinationCB.getSelectedItem();
                            java.util.Date Date = dateDP.getDate();

                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            String DateFormated = sdf.format(Date);

                            infoMessage("Booking Done", "Alert !!");

                            String selectQuery1 = "select * from bus_details where bus_source='" + source + "' and bus_dest='" + destination + "' and bus_date = '" + DateFormated + "' ";
                            ResultSet rs1 = stat.executeQuery(selectQuery1);

                            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
                            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                            
                            if(i == 1){
                                String updateQuery1 = "update availability set status='" + status + "' where bus_no='" + bus_no + "'  and journey_date='" + bus_date + "' and seat='"+seatno+"'" ;
                                int k=stat.executeUpdate(updateQuery1);
                            }

                        }
                    }
                    

                }
            } catch (Exception e) {
                System.out.println(e);
            }
           Table1(); 

        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void destinationCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationCBActionPerformed
    GridLayout gl;
    public JFrame BookingFormFrame;
    public JPanel BookingFormPanel;
    public JLabel l1, l3, l4, l5, l6, l7, l8, l11, l13, l14, l15, l16, l17, l18, seatnoL,  fnameL, lnameL;
    public JComboBox seatCB;
    public JTextField t1, t3, t4;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dateDP;
    private javax.swing.JComboBox<String> destinationCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> sourceCB;
    // End of variables declaration//GEN-END:variables
}
